security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Enseignant:
            algorithm: auto
        App\Entity\Administrateur:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
         enseignants:
            entity:
                class: App\Entity\Enseignant
                property: mail  
         administrateurs:
            entity:
                class: App\Entity\Administrateur
                property: mail
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        administrateur:
            pattern: ^/admin
            lazy: true
            provider: administrateurs
            form_login:
                login_path: app_administrateur_login
                check_path: app_administrateur_login
                default_target_path: /admin
                username_parameter: mail
                password_parameter: motDePasse
            logout:
                path: app_administrateur_logout
                target: /
                invalidate_session: true

        enseignant:
            pattern: ^/enseignant
            lazy: true
            provider: enseignants
            form_login:
                login_path: app_enseignant_login
                check_path: app_enseignant_login
                default_target_path: /
                username_parameter: mail
                password_parameter: motDePasse
            logout:
                path: app_enseignant_logout
                target: /
                invalidate_session: true
                

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - {path: ^/enseignant/login, roles: PUBLIC_ACCESS }
        - {path: ^/enseignant/logout, roles: PUBLIC_ACCESS }
        - {path: ^/enseignant, roles: ROLE_ENSEIGNANT }
        - {path: ^/admin/login, roles: PUBLIC_ACCESS }
        - {path: ^/admin/logout, roles: PUBLIC_ACCESS }
        - {path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
